name: narupatools-docs
channels:
  - conda-forge
  - irl
  - omnia
  - alexjbinnie
dependencies:
  - python=3.8
  - numpy>=1.20.*
  - narupa-server=0.1.2061
  - mdtraj=1.9.*
  - lammps=2021.02.10
  - lxml=4.6.*
  - infinite-sets=1.0.*
  - sphinx=3.5.*
  - sphinx_autodoc_typehints=1.12.*