# Conda environment for running narupatools and associated jupyter notebooks.
name: narupatools
channels:
  - conda-forge
  - irl
  - alexjbinnie
dependencies:
  - python>=3.8
  - numpy>=1.20.*
  - openmm>=7.5.*
  - narupa-server=0.1.2085
  - mdtraj=1.9.*
  - lammps=2021.02.10
  - lxml=4.6.*
  - infinite-sets=1.0.*
  - plotly=4.14.*
  - nglview=2.7.*
  - pip
  - pip:
    - ./narupatools
