channels:
- conda-forge
- irl
- alexjbinnie
dependencies:
- black=21.*
- flake8-bugbear=21.*
- flake8-builtins=1.5.*
- flake8-comprehensions=3.*
- flake8-docstrings=1.*
- flake8-pyi=20.*
- flake8-rst-docstrings=0.2.*
- flake8-simplify=0.14.*
- flake8=3.9.*
- hypothesis=6.*
- infinite-sets=1.*
- ipykernel
- isort=5.*
- lxml=4.*
- mdtraj=1.*
- mypy=0.910
- mypy_extensions=0.4.*
- narupa-server=0.1.2085
- nbsphinx=0.8.*
- nglview=3.*
- numpy>=1.21.*
- openmm>=7.*
- pip
- plotly=4.*
- pytest-timeout=1.4.*
- pytest-xdist=2.*
- pytest=6.*
- python>=3.8
- quaternion
- rdkit=2021.*
- sphinx-autodoc-typehints=1.12.*
- sphinx=3.5.*
- pip:
  - ./narupatools
name: narupatools
