# Conda environment for unit testing
name: narupatools-test
channels:
  - conda-forge
  - irl
  - alexjbinnie
dependencies:
  - python=3.8
  - numpy>=1.20.*
  - narupa-server=0.1.2061
  - openmm<7.6.0
  - mdtraj=1.9.*
  - lammps=2020.10.29
  - pytest=6.2.*
  - pytest-xdist=2.2.*
  - pytest-timeout=1.4.*
  - hypothesis=6.8.*
  - lxml=4.6.*
  - infinite-sets=1.0.*
