package:
  name: "narupatools"
  version: "0.2.0"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  build:
    - python
  run:
    - python>=3.8
    - numpy>=1.20.*
    - narupa-server=0.1.2061
    - mdtraj>=1.9.*
    - lxml>=4.6.*
    - pip
    - infinite-sets==1.0.*

about:
  home: https://github.com/alexjbinnie/narupatools
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  summary: "Extensions and utilities for working with the Narupa framework."

extra:
  recipe-maintainers:
    - alexjbinnie
