# Conda environment for running narupatools and associated jupyter notebooks.
name: narupatools
channels:
  - conda-forge
  - irl
  - alexjbinnie
dependencies:
# Minimum Python. Required for assignment expressions, positional-only arguments
  - python>=3.8
# Minimum NumPy. Required for numpy.typing.NDArray
  - numpy>=1.21.*
# Packages required by narupatools directly
  - lxml=4.*
  - infinite-sets=1.*
  - quaternion
# Exact Narupa version. Required as breaking changes can occur
  - narupa-server=0.1.2085
# Compatible Packages
  - mdtraj=1.*
  - openmm>=7.6
  - rdkit=2021.*
  - lammps=2021.09.29
# Packages required to run jupyter notebooks
  - plotly=5.*
  - nglview=3.*
# Pip install narupatools
  - pip
  - pip:
    - ./narupatools
