# Conda environment for running narupatools and associated jupyter notebooks.
name: narupatools
channels:
  - conda-forge
  - irl
  - alexjbinnie
dependencies:
# Minimum Python. Required for assignment expressions, positional-only arguments
  - python>=3.8
# Minimum NumPy. Required for numpy.typing.NDArray
  - numpy>=1.21.*
# Packages required by narupatools directly
  - lxml=4.*
  - infinite-sets=1.*
  - quaternion
# Exact Narupa version. Required as breaking changes can occur
  - narupa-server=0.1.2061
# Compatible Packages. OpenMM cannot be 7.6.0 due to namespace changes that break Narupa
  - mdtraj=1.9.*
  - lammps=2020.10.09
  - openmm<=7.5.*
  - rdkit=2021.*
# Packages required to run jupyter notebooks
  - plotly=4.14.*
  - nglview=2.7.*
# Pip install narupatools
  - pip
  - pip:
    - ./narupatools
