from typing import Any, Iterator

from tables.node import Node

class Group:
    def __getattr__(self, name: str) -> Any: ...
    @property
    def _v_nchildren(self) -> int: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __contains__(self, name: str) -> bool: ...

class RootGroup(Group): ...
