from typing import Any, List

from lammps.numpy_wrapper import numpy_wrapper

class lammps:
    def extract_compute(self, id: str, style: int, type: int) -> Any: ...
    def gather_atoms(self, name: str, type: int, count: int) -> Any: ...
    def get_natoms(self) -> int: ...
    def scatter_atoms(self, name: str, type: int, count: int, data: Any) -> None: ...
    @property
    def numpy(self) -> numpy_wrapper: ...
    @property
    def installed_packages(self) -> List[str]: ...
