# This file is part of narupatools (https://github.com/alexjbinnie/narupatools).
# Copyright (c) Alex Jamieson-Binnie. All rights reserved.
#
# narupatools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# narupatools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with narupatools.  If not, see <http://www.gnu.org/licenses/>.
from typing import List

import numpy as np
from MDAnalysis import Universe
from MDAnalysis.core.topologyobjects import TopologyGroup

class Group:
    @property
    def ix(self) -> np.ndarray: ...
    @property
    def indices(self) -> np.ndarray: ...
    def __len__(self) -> int: ...

class ResidueGroup(Group):
    @property
    def segindices(self) -> np.ndarray: ...
    @property
    def resnames(self) -> List[str]: ...
    @property
    def resids(self) -> List[str]: ...

class SegmentGroup(Group):
    @property
    def segids(self) -> np.ndarray: ...

class AtomGroup(Group):
    @property
    def universe(self) -> Universe: ...
    @property
    def n_atoms(self) -> int: ...
    @property
    def n_residues(self) -> int: ...
    @property
    def n_segments(self) -> int: ...
    @property
    def atoms(self) -> AtomGroup: ...
    @property
    def residues(self) -> ResidueGroup: ...
    @property
    def segments(self) -> SegmentGroup: ...
    @property
    def positions(self) -> np.ndarray: ...
    @property
    def resindices(self) -> np.ndarray: ...
    @property
    def names(self) -> np.ndarray: ...
    @property
    def bonds(self) -> TopologyGroup: ...
    @property
    def types(self) -> np.ndarray: ...
    @property
    def masses(self) -> np.ndarray: ...
    @property
    def elements(self) -> np.ndarray: ...
    @property
    def dimensions(self) -> np.ndarray: ...
    @property
    def velocities(self) -> np.ndarray: ...
    @property
    def forces(self) -> np.ndarray: ...
    @property
    def charges(self) -> np.ndarray: ...
