import numpy as np

class TopologyAttr:
    def __init__(self, values: np.ndarray): ...

class Resnames(TopologyAttr): ...
class Atomnames(TopologyAttr): ...
class Elements(TopologyAttr): ...
class Bonds(TopologyAttr): ...
class Charges(TopologyAttr): ...
class Masses(TopologyAttr): ...
class Atomtypes(TopologyAttr): ...
