import numpy as np

class Rotation:
    @classmethod
    def from_quat(cls, quat: np.ndarray) -> Rotation: ...
    def as_matrix(self) -> np.ndarray: ...
    @classmethod
    def from_rotvec(cls, rotvec: np.ndarray, degrees: bool = ...): ...
    @classmethod
    def random(cls) -> Rotation: ...
    def apply(self, vector: np.ndarray) -> np.ndarray: ...
