name: Conda Package

on: push

jobs:
  run-linters:
    name: Build Conda package
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8

      - name: Install conda build
        run: |
          conda install conda-build

      - name: Get Version
        run: |
          echo "VERSION=$(cat narupatools/src/narupatools/VERSION)" >> $GITHUB_ENV

      - name: Run conda build
        run: |
          conda build narupatools -c conda-forge -c irl -c omnia -c alexjbinnie
          echo "conda_package=$(conda build narupatools -c conda-forge -c irl -c omnia -c alexjbinnie --output)" >> $GITHUB_ENV

      - name: Test conda install
        run: |
          conda install "${{ env.conda_package }}" -c conda-forge -c irl -c omnia -c alexjbinnie

      - uses: actions/upload-artifact@v2
        with:
          name: Conda Package
          path: "${{ env.conda_package }}"