name: Conda Package

on: push

jobs:
  run-linters:
    name: Build Conda package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache lint-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('lint-environment.yml') }}

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Get conda build
        run: |
          conda install conda-build

      - name: Run conda build
        run: |
          conda build narupatools --output-folder build