name: Documentation

on: push

jobs:
  run-linters:
    name: Compile documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Create environment file
        run: |
          conda install -c conda-forge conda-merge
          conda-merge environment.yml docs-environment.yml > gitlab-environment.yml

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache gitlab-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('gitlab-environment.yml') }}

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: gitlab-environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Run sphinx doctest
        run: |
          sphinx-build -b doctest source build

      - name: Run sphinx
        run: |
          sphinx-build -b html source build