name: Static Analysis

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Create environment file
        run: |
          pip install conda-merge
          conda-merge .environments/base.yml .environments/tests.yml .environments/static-analysis.yml > gitlab-environment.yml

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache lint-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('lint-environment.yml') }}

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: gitlab-environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Run black
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_args: narupatools stubs
          black_command_prefix: python -m
          auto_fix: true

      - name: Run flake8
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          flake8_args: narupatools stubs
          flake8_command_prefix: python -m
          auto_fix: true

      - name: Run mypy
        uses: wearerequired/lint-action@v1
        with:
          mypy: true
          mypy_args: --install-types --non-interactive narupatools/src narupatools/tests
          mypy_command_prefix: python -m
          auto_fix: true