name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache lint-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('lint-environment.yml') }}

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: lint-environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Run black
        run: |
          black --check narupatools stubs

      - name: Run flake8
        run: |
          flake8 narupatools stubs

      - name: Run mypy
        run: |
          mypy narupatools/src narupatools/tests