name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: narupatools-lint
          environment-file: lint-environment.yml

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Run black
        uses: wearerequired/lint-action@v1
        with:
          black: true

      - name: Run flake8
        uses: wearerequired/lint-action@v1
        with:
          flake8: true

      - name: Run mypy
        uses: wearerequired/lint-action@v1
        with:
          mypy: true