name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: lint-environment.yml

      - name: Run black
        run: |
          black narupatools stubs

      - name: Run flake8
        run: |
          flake8 narupatools stubs

      - name: Run mypy
        run: |
          narupatools/src narupatools/tests